/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  safelist: [
    "grid-cols-1", "grid-cols-2", "grid-cols-3", "grid-cols-4", "grid-cols-5",
    "border-l-primary-container", "border-l-tertiary-fixed-dim",
    "text-primary-container", "text-tertiary-fixed-dim",
    "bg-primary-container", "bg-tertiary-fixed-dim",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#e9feff",
        "secondary": "#ffb1c0",
        "tertiary": "#fff9f5",
        "on-error": "#690005",
        "on-surface-variant": "#b9caca",
        "secondary-fixed-dim": "#ffb1c0",
        "inverse-primary": "#00696e",
        "primary-container": "#00f5ff",
        "surface-container-high": "#2a292f",
        "surface-container-highest": "#35343a",
        "on-error-container": "#ffdad6",
        "surface-container": "#1f1f25",
        "surface-dim": "#131318",
        "secondary-container": "#e00363",
        "on-primary-fixed": "#002021",
        "inverse-on-surface": "#303036",
        "error": "#ffb4ab",
        "on-primary-container": "#006c71",
        "background": "#131318",
        "on-primary": "#003739",
        "on-secondary-container": "#fff6f6",
        "on-primary-fixed-variant": "#004f53",
        "tertiary-fixed-dim": "#ffba20",
        "error-container": "#93000a",
        "outline": "#849495",
        "surface-container-lowest": "#0e0e13",
        "primary-fixed-dim": "#00dce5",
        "inverse-surface": "#e4e1e9",
        "surface-container-low": "#1b1b20",
        "surface": "#131318",
        "tertiary-fixed": "#ffdea8",
        "primary-fixed": "#63f7ff",
        "surface-tint": "#00dce5",
        "secondary-fixed": "#ffd9df",
        "surface-variant": "#35343a",
        "on-tertiary-fixed": "#271900",
        "on-surface": "#e4e1e9",
        "on-secondary-fixed": "#3f0017",
        "tertiary-container": "#ffd895",
        "on-secondary": "#660029",
        "on-background": "#e4e1e9",
        "on-tertiary-container": "#805b00",
        "on-secondary-fixed-variant": "#90003d",
        "surface-bright": "#39383e",
        "on-tertiary": "#412d00",
        "on-tertiary-fixed-variant": "#5e4200",
        "outline-variant": "#3a494a",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
