/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#003824",
        "surface-variant": "#31353c",
        "tertiary": "#ffbcb7",
        "error": "#ffb4ab",
        "inverse-on-surface": "#2d3137",
        "on-surface-variant": "#d8c3ad",
        "tertiary-fixed": "#ffdad7",
        "surface-dim": "#10141a",
        "surface": "#10141a",
        "surface-container": "#1c2026",
        "inverse-surface": "#dfe2eb",
        "primary": "#ffc174",
        "secondary-container": "#00a572",
        "on-primary": "#472a00",
        "inverse-primary": "#855300",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#2a1700",
        "on-tertiary": "#68000a",
        "tertiary-container": "#ff938c",
        "surface-tint": "#ffb95f",
        "on-secondary-fixed": "#002113",
        "outline": "#a08e7a",
        "on-background": "#dfe2eb",
        "surface-container-highest": "#31353c",
        "on-primary-fixed-variant": "#653e00",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-container-high": "#262a31",
        "on-tertiary-container": "#8d0012",
        "surface-bright": "#353940",
        "on-error": "#690005",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#930013",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#181c22",
        "surface-container-lowest": "#0a0e14",
        "background": "#10141a",
        "primary-container": "#f59e0b",
        "on-tertiary-fixed": "#410004",
        "on-secondary-container": "#00311f",
        "on-primary-container": "#613b00",
        "outline-variant": "#534434",
        "secondary": "#4edea3",
        "error-container": "#93000a",
        "primary-fixed-dim": "#ffb95f",
        "on-surface": "#dfe2eb",
        "primary-fixed": "#ffddb8",
      },
      fontFamily: {
        headline: ['"Be Vietnam Pro"', '"Hind Siliguri"', "sans-serif"],
        body: ['"Inter"', '"Hind Siliguri"', "sans-serif"],
        label: ['"Inter"', '"Hind Siliguri"', "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
